# Generated by Django 4.0.4 on 2022-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_creation',
            field=models.DateField(null=True),
        ),
    ]
